version: '3'

services:
#  rest_api:
#    build: .
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    container_name: resize_image_django
#    volumes:
#      - .:/app
#
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

  db:
    image: postgres
    container_name: "resize"
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=dav

