# Generated by Django 3.0.6 on 2020-05-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import img_upload_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=25, unique=True)),
                ('img_description', models.TextField(blank=True, max_length=250)),
                ('img_format', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favourite', models.BooleanField(default=False)),
                ('uploaded_image', models.ImageField(upload_to=img_upload_api.models.owner_directory_path)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share_user', models.ManyToManyField(blank=True, null=True, related_name='shared_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styled_img_name', models.CharField(max_length=25, unique=True)),
                ('styled_image', models.ImageField(upload_to=img_upload_api.models.owner_directory_path_styles)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_upload_api.Images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
